spring:
  datasource:
    url: jdbc:mysql://localhost:3310/chikha-subscription?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics, refresh, env

logging:
  level:
    root: INFO